language: node_js
node_js: 12

services:
  - postgresql

before_script:
  - psql -c "create user helper with encrypted password 'helper';" -U postgres
  - psql -c "create database accounts_test;" -U postgres
  - psql -c "grant all privileges on database accounts_test to helper" -U postgres
script:
  - yarn lint
  - yarn test
