#!/bin/bash
set -e

export PGPASSWORD=$POSTGRES_PASSWORD;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $CONTRCT_HELPER_DB_USER WITH PASSWORD '$CONTRCT_HELPER_DB_PASS';
  CREATE DATABASE $CONTRCT_HELPER_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $CONTRCT_HELPER_DB_NAME TO $CONTRCT_HELPER_DB_USER;
  \ connect $CONTRCT_HELPER_DB_NAME $CONTRCT_HELPER_DB_USER
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $EXPLORER_DB_USER WITH PASSWORD '$EXPLORER_DB_PASS';
  CREATE DATABASE $EXPLORER_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $EXPLORER_DB_NAME TO $EXPLORER_DB_USER;
  \ connect $EXPLORER_DB_NAME $EXPLORER_DB_USER
EOSQL