#!/bin/bash
set -e

export PGPASSWORD=$POSTGRES_PASSWORD;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $CONTRACT_HELPER_DB_USER WITH PASSWORD '$CONTRACT_HELPER_DB_PASS';
  CREATE DATABASE $CONTRACT_HELPER_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $CONTRACT_HELPER_DB_NAME TO $CONTRACT_HELPER_DB_USER;

  CREATE USER $EXPLORER_DB_USER WITH PASSWORD '$EXPLORER_DB_PASS';
  CREATE DATABASE $EXPLORER_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $EXPLORER_DB_NAME TO $EXPLORER_DB_USER;

  CREATE USER $ANALYTICS_DB_USER WITH PASSWORD '$ANALYTICS_DB_PASS';
  CREATE DATABASE $ANALYTICS_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $ANALYTICS_DB_NAME TO $ANALYTICS_DB_USER;

  CREATE USER $TELEMETRY_DB_USER WITH PASSWORD '$TELEMETRY_DB_PASS';
  CREATE DATABASE $TELEMETRY_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $TELEMETRY_DB_NAME TO $TELEMETRY_DB_USER;
EOSQL
