version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    container_name: pg-docker
    restart: always
    environment:
      - POSTGRES_USER=helper
      - POSTGRES_PASSWORD=helper
      - POSTGRES_DB=accounts_development
      - APP_DB_USER=helper
      - APP_DB_PASS=helper
      - APP_DB_NAME=accounts_development
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-db:/docker-entrypoint-initdb.d/
      - ./postgres-db/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "helper" ]
      timeout: 45s
      interval: 10s
      retries: 10
    depends_on: 
      - validator-1
      - validator-2
      - validator-3
      - validator-4


  validator-1:
    image: quantiksolutions/near-core:latest
    volumes:
      - ../configs/ta_a:/srv/near
    networks:
      back-tier:
        ipv4_address: 172.20.0.2
    ports:
      - "3030:3030"
      - "24567:24567"


  validator-2:
    image: quantiksolutions/near-core:latest
    volumes:
      - ../configs/ta_b:/srv/near
    networks:
      back-tier:
        ipv4_address: 172.20.0.3
    ports:
      - "3031:3030"
      - "24568:24567"


  validator-3:
    image: quantiksolutions/near-core:latest   
    volumes:
      - ../configs/ta_c:/srv/near
    networks:
      back-tier:
        ipv4_address: 172.20.0.4
    ports:
      - "3032:3030"
      - "24569:24567"
      
  validator-4:
    image: quantiksolutions/near-core:latest
    volumes:
      - ../configs/ta_d:/srv/near
    networks:
      back-tier:
        ipv4_address: 172.20.0.5
    ports:
      - "3033:3030"
      - "24570:24567"


  contract-helper:
    image: nearcore_local_contract_helper:latest
    build:
      context: ./contract-helper/
      dockerfile: ./Dockerfile
      cache_from:
        - nearcore_local_contract_helper:latest
    env_file:
      - ./contract-helper/.env
    depends_on:
      - db
      - validator-1
      - validator-2
      - validator-3
      - validator-4
    networks:
      back-tier:
        ipv4_address: 172.20.0.6
    ports:
      - "3000:3000"
    command: yarn start
    

  near-wallet:
    image: nearcore_local_wallet:latest
    build: 
      context: ./near-wallet/
      dockerfile: ./Dockerfile
      cache_from:
        - nearcore_local_wallet:latest
    networks:
      back-tier:
        ipv4_address: 172.20.0.7
    ports:
      - "3004:3004"
    depends_on:
      - contract-helper


networks:
  back-tier:
    ipam:
      config:
        - subnet: 172.20.0.0/24

